import axios from "axios";
import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import jsPDF from "jspdf";
import { Bar } from 'react-chartjs-2';
import { Chart, registerables } from 'chart.js';
import "./styles/inventory.css"; // Import your custom CSS

Chart.register(...registerables);

export default function Inventory() {
  const [users, setUsers] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [showChart, setShowChart] = useState(false); // State for showing modal
  const navigate = useNavigate();

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = () => {
    axios
      .get("http://localhost:3001/inventory")
      .then((result) => setUsers(result.data))
      .catch((err) => console.log(err));
  };

  const handleDelete = (id) => {
    Swal.fire({
      title: "Are you sure?",
      text: "You won't be able to revert this!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText: "Yes, delete it!",
    }).then((result) => {
      if (result.isConfirmed) {
        axios
          .delete(`http://localhost:3001/inventory/${id}`)
          .then(() => {
            Swal.fire("Deleted!", "Your item has been deleted.", "success");
            fetchUsers();
          })
          .catch((err) => console.error(err));
      }
    });
  };

  const handleViewItem = (user) => {
    if (user.Quantity > 0) {
      axios
        .put(`http://localhost:3001/inventory/${user._id}`, {
          ...user,
          Quantity: user.Quantity - 1,
        })
        .then(() => {
          Swal.fire("Success!", "Item viewed. Quantity decreased by 1.", "success");
          fetchUsers();
        })
        .catch((err) => console.error(err));
    } else {
      Swal.fire("Out of stock", "This item is out of stock!", "warning");
    }
  };
//generate report
  const handleGenerateReport = () => {
    const doc = new jsPDF();
    const currentDate = new Date().toLocaleDateString();
    const currentTime = new Date().toLocaleTimeString();

    doc.setFontSize(20);
    doc.text("Inventory Report", 10, 10);

    doc.setFontSize(12);
    doc.text(`Generated on: ${currentDate} at ${currentTime}`, 10, 20);

    doc.line(10, 25, 200, 25);

    const headers = ["Item Name", "Item ID", "Quantity", "Minimum Amount"];
    const data = users.map(user => [
      user.ItemName,
      user.ItemId,
      user.Quantity,
      user.MinimumAmount,
    ]);

    doc.autoTable({
      head: [headers],
      body: data,
      startY: 30,
      headStyles: { fillColor: [173, 216, 230], textColor: [0, 0, 0], fontSize: 12 },
      styles: { fontSize: 10, cellPadding: 5 },
    });

    const footerY = doc.autoTable.previous.finalY + 10;
    doc.line(10, footerY, 200, footerY);
    doc.setFontSize(10);
    doc.text("Generated by: Levaggio", 10, footerY + 5);

    doc.save("inventory_report.pdf");
  };

  const filteredUsers = users.filter(
    (user) =>
      user.ItemName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      user.ItemId.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const generateRandomColors = (num) => {
    const colors = [];
    for (let i = 0; i < num; i++) {
      const color = `rgba(${Math.floor(Math.random() * 255)}, ${Math.floor(
        Math.random() * 255
      )}, ${Math.floor(Math.random() * 255)}, 0.6)`;
      colors.push(color);
    }
    return colors;
  };

  const barChartData = {
    labels: users.map(user => user.ItemName),
    datasets: [
      {
        label: 'Quantity',
        data: users.map(user => user.Quantity),
        backgroundColor: generateRandomColors(users.length),
        borderColor: 'rgba(0, 0, 0, 0.1)',
        borderWidth: 1,
        hoverBackgroundColor: generateRandomColors(users.length),
        hoverBorderColor: 'rgba(0, 0, 0, 0.5)',
      },
    ],
  };

  const barChartOptions = {
    scales: {
      y: {
        beginAtZero: true,
      },
    },
    plugins: {
      legend: {
        labels: {
          font: {
            size: 14,
          },
        },
      },
      tooltip: {
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        titleFont: {
          size: 16,
        },
        bodyFont: {
          size: 14,
        },
      },
    },
    responsive: true,
    maintainAspectRatio: false,
  };

  return (
    <div className="d-flex vh-100 justify-content-center align-items-center">
      <div
        className="w-75 bg-white rounded p-4 shadow-lg"
        style={{
          border: "2px solid #8B0000",
          height: "80vh",
          overflowY: "auto",
          marginTop: "100px",
        }}
      >
        <Link
          to="/inventorycreate"
          className="btn btn-success mb-3"
          style={{ width: "150px" }}
        >
          Add +
        </Link>

        <Link to="/low-inventory" className="btn btn-warning mb-3 ms-2">
          Low Inventory
        </Link>
        <button
          className="btn btn-info mb-3 ms-2"
          onClick={handleGenerateReport}
        >
          Generate Report
        </button>

        <button
          className="btn btn-primary mb-3 ms-2"
          onClick={() => setShowChart(true)}
        >
          Show Charts
        </button>

        <input
          type="text"
          className="form-control mb-3"
          placeholder="Search by Item Name or Item ID"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />

        <div style={{ maxHeight: "50vh", overflowY: "scroll" }}>
          <table className="table table-striped">
            <thead style={{ backgroundColor: "#8B0000", color: "white" }}>
              <tr>
                <th>Item Name</th>
                <th>Item ID</th>
                <th>Quantity</th>
                <th>Minimum Quantity</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredUsers.map((user) => (
                <tr key={user._id}>
                  <td>{user.ItemName}</td>
                  <td>{user.ItemId}</td>
                  <td>{user.Quantity}</td>
                  <td>{user.MinimumAmount}</td>
                  <td>
                    <Link
                      to={`/inventoryupdate/${user._id}`}
                      className="btn btn-warning"
                    >
                      Update
                    </Link>
                    <button
                      onClick={() => handleViewItem(user)}
                      className="btn btn-info ms-2"
                    >
                      Used
                    </button>
                    <button
                      onClick={() => handleDelete(user._id)}
                      className="btn btn-danger ms-2"
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {showChart && (
          <div className="modal-overlay">
            <div className="modal-content">
              <span className="close" onClick={() => setShowChart(false)}>
                &times;
              </span>
              <h4 className="text-center">Inventory Quantity Chart</h4>
              <div style={{ height: "400px", width: "100%" }}>
                <Bar data={barChartData} options={barChartOptions} />
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
